/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeatpumpIndexRouteImport } from './routes/heatpump/index'
import { Route as HeatpumpCostTrackingRouteImport } from './routes/heatpump/cost-tracking'
import { Route as HeatpumpAiAnalysisRouteImport } from './routes/heatpump/ai-analysis'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatpumpIndexRoute = HeatpumpIndexRouteImport.update({
  id: '/heatpump/',
  path: '/heatpump/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatpumpCostTrackingRoute = HeatpumpCostTrackingRouteImport.update({
  id: '/heatpump/cost-tracking',
  path: '/heatpump/cost-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatpumpAiAnalysisRoute = HeatpumpAiAnalysisRouteImport.update({
  id: '/heatpump/ai-analysis',
  path: '/heatpump/ai-analysis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/heatpump/ai-analysis': typeof HeatpumpAiAnalysisRoute
  '/heatpump/cost-tracking': typeof HeatpumpCostTrackingRoute
  '/heatpump/': typeof HeatpumpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/heatpump/ai-analysis': typeof HeatpumpAiAnalysisRoute
  '/heatpump/cost-tracking': typeof HeatpumpCostTrackingRoute
  '/heatpump': typeof HeatpumpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/heatpump/ai-analysis': typeof HeatpumpAiAnalysisRoute
  '/heatpump/cost-tracking': typeof HeatpumpCostTrackingRoute
  '/heatpump/': typeof HeatpumpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/heatpump/ai-analysis'
    | '/heatpump/cost-tracking'
    | '/heatpump/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/heatpump/ai-analysis'
    | '/heatpump/cost-tracking'
    | '/heatpump'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/heatpump/ai-analysis'
    | '/heatpump/cost-tracking'
    | '/heatpump/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  HeatpumpAiAnalysisRoute: typeof HeatpumpAiAnalysisRoute
  HeatpumpCostTrackingRoute: typeof HeatpumpCostTrackingRoute
  HeatpumpIndexRoute: typeof HeatpumpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatpump/': {
      id: '/heatpump/'
      path: '/heatpump'
      fullPath: '/heatpump/'
      preLoaderRoute: typeof HeatpumpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatpump/cost-tracking': {
      id: '/heatpump/cost-tracking'
      path: '/heatpump/cost-tracking'
      fullPath: '/heatpump/cost-tracking'
      preLoaderRoute: typeof HeatpumpCostTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatpump/ai-analysis': {
      id: '/heatpump/ai-analysis'
      path: '/heatpump/ai-analysis'
      fullPath: '/heatpump/ai-analysis'
      preLoaderRoute: typeof HeatpumpAiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  HeatpumpAiAnalysisRoute: HeatpumpAiAnalysisRoute,
  HeatpumpCostTrackingRoute: HeatpumpCostTrackingRoute,
  HeatpumpIndexRoute: HeatpumpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
