/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeatpumpIndexRouteImport } from './routes/heatpump/index'
import { Route as HeatpumpScatterRouteImport } from './routes/heatpump/scatter'
import { Route as HeatpumpDataRouteImport } from './routes/heatpump/data'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatpumpIndexRoute = HeatpumpIndexRouteImport.update({
  id: '/heatpump/',
  path: '/heatpump/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatpumpScatterRoute = HeatpumpScatterRouteImport.update({
  id: '/heatpump/scatter',
  path: '/heatpump/scatter',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatpumpDataRoute = HeatpumpDataRouteImport.update({
  id: '/heatpump/data',
  path: '/heatpump/data',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/heatpump/data': typeof HeatpumpDataRoute
  '/heatpump/scatter': typeof HeatpumpScatterRoute
  '/heatpump/': typeof HeatpumpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/heatpump/data': typeof HeatpumpDataRoute
  '/heatpump/scatter': typeof HeatpumpScatterRoute
  '/heatpump': typeof HeatpumpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/heatpump/data': typeof HeatpumpDataRoute
  '/heatpump/scatter': typeof HeatpumpScatterRoute
  '/heatpump/': typeof HeatpumpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/heatpump/data'
    | '/heatpump/scatter'
    | '/heatpump/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/heatpump/data' | '/heatpump/scatter' | '/heatpump'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/heatpump/data'
    | '/heatpump/scatter'
    | '/heatpump/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  HeatpumpDataRoute: typeof HeatpumpDataRoute
  HeatpumpScatterRoute: typeof HeatpumpScatterRoute
  HeatpumpIndexRoute: typeof HeatpumpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatpump/': {
      id: '/heatpump/'
      path: '/heatpump'
      fullPath: '/heatpump/'
      preLoaderRoute: typeof HeatpumpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatpump/scatter': {
      id: '/heatpump/scatter'
      path: '/heatpump/scatter'
      fullPath: '/heatpump/scatter'
      preLoaderRoute: typeof HeatpumpScatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatpump/data': {
      id: '/heatpump/data'
      path: '/heatpump/data'
      fullPath: '/heatpump/data'
      preLoaderRoute: typeof HeatpumpDataRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  HeatpumpDataRoute: HeatpumpDataRoute,
  HeatpumpScatterRoute: HeatpumpScatterRoute,
  HeatpumpIndexRoute: HeatpumpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
