// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OctopusCosyAnalyser.ApiService.Data;

#nullable disable

namespace OctopusCosyAnalyser.ApiService.Migrations
{
    [DbContext(typeof(CosyDbContext))]
    [Migration("20260401213804_RemoveEfficiencyTracking")]
    partial class RemoveEfficiencyTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OctopusCosyAnalyser.ApiService.Models.ConsumptionReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Consumption")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("ConsumptionDelta")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Demand")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ReadAt")
                        .IsUnique();

                    b.ToTable("ConsumptionReadings");
                });

            modelBuilder.Entity("OctopusCosyAnalyser.ApiService.Models.HeatPumpDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Euid")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeterSerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Mpan")
                        .HasColumnType("text");

                    b.Property<int?>("PropertyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("HeatPumpDevices");
                });

            modelBuilder.Entity("OctopusCosyAnalyser.ApiService.Models.HeatPumpSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("CoefficientOfPerformance")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool?>("ControllerConnected")
                        .HasColumnType("boolean");

                    b.Property<string>("ControllerState")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("HeatOutputKilowatt")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal?>("HeatingFlowTempAllowableMaxCelsius")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("HeatingFlowTempAllowableMinCelsius")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("HeatingFlowTemperatureCelsius")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool?>("HeatingZoneHeatDemand")
                        .HasColumnType("boolean");

                    b.Property<string>("HeatingZoneMode")
                        .HasColumnType("text");

                    b.Property<decimal?>("HeatingZoneSetpointCelsius")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<bool?>("HotWaterZoneHeatDemand")
                        .HasColumnType("boolean");

                    b.Property<string>("HotWaterZoneMode")
                        .HasColumnType("text");

                    b.Property<decimal?>("HotWaterZoneSetpointCelsius")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("LifetimeEnergyInputKwh")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LifetimeHeatOutputKwh")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("OutdoorTemperatureCelsius")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("PowerInputKilowatt")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal?>("PrimarySensorTemperatureCelsius")
                        .HasColumnType("numeric");

                    b.Property<bool?>("PrimaryZoneHeatDemand")
                        .HasColumnType("boolean");

                    b.Property<string>("PrimaryZoneMode")
                        .HasColumnType("text");

                    b.Property<decimal?>("PrimaryZoneSetpointCelsius")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RoomHumidityPercentage")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("RoomSensorCode")
                        .HasColumnType("text");

                    b.Property<decimal?>("RoomTemperatureCelsius")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("SeasonalCoefficientOfPerformance")
                        .HasColumnType("numeric");

                    b.Property<string>("SensorReadingsJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("SnapshotTakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("WeatherCompensationEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("WeatherCompensationMaxCelsius")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("WeatherCompensationMinCelsius")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "SnapshotTakenAt")
                        .IsUnique();

                    b.ToTable("HeatPumpSnapshots");
                });

            modelBuilder.Entity("OctopusCosyAnalyser.ApiService.Models.OctopusAccountSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.ToTable("OctopusAccountSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
