using OctopusCosyAnalyser.ApiService.Data;
using OctopusCosyAnalyser.ApiService.Endpoints;
using OctopusCosyAnalyser.ApiService.Services;
using OctopusCosyAnalyser.ApiService.Workers;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// Add service defaults & Aspire client integrations.
builder.AddServiceDefaults();

// Add PostgreSQL DbContext
builder.AddNpgsqlDbContext<CosyDbContext>("cosydb");

// Add Octopus Energy API client
builder.Services.AddHttpClient<OctopusEnergyClient>();

// Add Tado API client
builder.Services.AddHttpClient<TadoClient>();

// Add Heat Pump Snapshot Worker
builder.Services.AddHostedService<HeatPumpSnapshotWorker>();

// Add services to the container.
builder.Services.AddProblemDetails();

// Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
builder.Services.AddOpenApi();

var app = builder.Build();

// Auto-migrate database on startup — handles both new tables and new columns
using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider.GetRequiredService<CosyDbContext>();

    // Create the database and all tables if DB doesn't exist at all
    await db.Database.EnsureCreatedAsync();

    // EnsureCreated does NOT alter existing tables or create new tables if DB already exists.
    // Run raw SQL to create any missing tables and add any missing columns.
    await EnsureMissingTablesAndColumnsAsync(db);
}

// Configure the HTTP request pipeline.
app.UseExceptionHandler();

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
}

string[] summaries = ["Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"];

app.MapGet("/", () => "API service is running. Navigate to /weatherforecast to see sample data.");

app.MapGet("/weatherforecast", () =>
{
    var forecast = Enumerable.Range(1, 5).Select(index =>
        new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        ))
        .ToArray();
    return forecast;
})
.WithName("GetWeatherForecast");

// Map Heat Pump endpoints
app.MapHeatPumpEndpoints();
app.MapAccountSettingsEndpoints();
app.MapTadoEndpoints();
app.MapEfficiencyEndpoints();

app.MapDefaultEndpoints();

app.Run();

/// <summary>
/// EnsureCreated() does NOT alter existing tables or create new tables when the DB already exists.
/// This method creates missing tables and adds missing columns via raw SQL.
/// </summary>
static async Task EnsureMissingTablesAndColumnsAsync(CosyDbContext db)
{
    // ── Create missing tables ───────────────────────────────────────
    try
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "TadoSettings" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Username" character varying(200) NOT NULL,
                "Password" character varying(500) NOT NULL,
                "HomeId" bigint,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc')
            )
            """);
    }
    catch { /* already exists */ }

    // ── Add missing columns to HeatPumpSnapshots ────────────────────
    var columns = new (string Name, string Type)[]
    {
        ("WeatherCompensationEnabled", "boolean"),
        ("WeatherCompensationMinCelsius", "numeric(10,2)"),
        ("WeatherCompensationMaxCelsius", "numeric(10,2)"),
        ("HeatingFlowTemperatureCelsius", "numeric(10,2)"),
        ("HeatingZoneSetpointCelsius", "numeric(10,2)"),
        ("HeatingZoneMode", "text"),
        ("HeatingZoneHeatDemand", "boolean"),
        ("RoomTemperatureCelsius", "numeric(10,2)"),
        ("RoomHumidityPercentage", "numeric(10,2)"),
        ("RoomSensorCode", "text"),
    };

    foreach (var (name, type) in columns)
    {
        try
        {
            var sql = "ALTER TABLE \"HeatPumpSnapshots\" ADD COLUMN IF NOT EXISTS \"" + name + "\" " + type;
            await db.Database.ExecuteSqlRawAsync(sql);
        }
        catch { /* already exists */ }
    }
}

record WeatherForecast(DateOnly Date, int TemperatureC, string? Summary)
{
    public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);
}

